// Shared portfolio data (ES + EN) — v2
window.PORTFOLIO_DATA = {
  meta: {
    name: "Sergio Guillén Pampliega",
    handle: "sergiogp.com",
    email: "sergio@sergiogp.com",
    phone: "+34 649 36 88 00",
    linkedin: "https://www.linkedin.com/in/sergioguillenpampliega",
    instagram: "https://www.instagram.com/sergiogp.ia/",
    location: "Murcia, España · Remoto Global",
    photoHero: "https://res.cloudinary.com/dg3peytgm/image/upload/v1769559402/Ponencia_Recorte_sgw3g4.jpg",
    photoAbout: "https://res.cloudinary.com/dg3peytgm/image/upload/v1769542383/yo_terraza_celohz.png",
    photoCaption: { es: "Ponencia Business+ 2025 — IA en Pymes", en: "Business+ 2025 Talk — AI for SMEs" },
  },
  es: {
    nav: {
      home: "Inicio", about: "Sobre mí", services: "Servicios", projects: "Proyectos",
      experience: "Experiencia", education: "Formación", stack: "Stack", skills: "Skills",
      faq: "FAQ", contact: "Contacto",
    },
    hero: {
      role: "Agente de Transformación Digital",
      tagline: "Inteligencia artificial\ny automatización para escalar tu negocio.",
      sub: "Más de 3 años optimizando procesos y transformando empresas. Convierto la tecnología en tu mayor ventaja competitiva.",
      ctaPrimary: "Consultoría gratuita",
      ctaSecondary: "Ver servicios",
      status: "Disponible para nuevos proyectos",
    },
    about: {
      kicker: "// Sobre mí",
      title: "Estrategia, IA y automatización al servicio de tu negocio.",
      body: [
        "Soy Sergio Guillén Pampliega. Graduado y formado en Inteligencia Artificial, Automatización de Procesos, Marketing y Transformación Digital.",
        "Mi objetivo es hacer a las empresas más óptimas, eficientes y competitivas. Lo consigo liberando tiempo, desarrollando sistemas para una mejor toma de decisiones y digitalizando procesos clave.",
        "Todos los servicios y soluciones son personalizados para cada cliente y proyecto, asegurando compromiso y resultados tangibles. Sin humo y sin sobre-ingeniería.",
      ],
      credentials: ["Harvard University", "ENAE Business School", "Universidad de Murcia"],
      stats: [
        { k: "ESPECIALIZACIÓN", v: "IA · Automatización · Marketing", icon: "brain" },
        { k: "MODALIDAD", v: "Freelance · Remoto Global", icon: "globe" },
        { k: "UBICACIÓN", v: "Murcia, España", icon: "pin" },
      ],
    },
    services: {
      kicker: "// Servicios",
      title: "Cuatro áreas, una visión integral.",
      areas: [
        {
          id: "01", label: "Soluciones IA",
          desc: "Implementación de inteligencia artificial para maximizar eficiencia y rentabilidad.",
          items: [
            { title: "Chatbots inteligentes", desc: "Atención al cliente automatizada 24/7 con procesamiento de lenguaje natural para respuestas humanas y precisas.", icon: "chat" },
            { title: "Asistentes RAG", desc: "Sistemas que leen tu documentación interna para responder consultas de empleados o clientes al instante.", icon: "brain" },
            { title: "Generación de contenido", desc: "Creación masiva y personalizada de textos, informes y copys de marketing manteniendo tu tono de marca.", icon: "spark" },
            { title: "Segmentación predictiva", desc: "Algoritmos que analizan tus datos para predecir comportamientos de compra y segmentar audiencias.", icon: "target" },
            { title: "Data Analytics & BI", desc: "Dashboards interactivos que transforman datos brutos en insights visuales para la toma de decisiones.", icon: "chart" },
            { title: "Meeting Intelligence", desc: "Transcripción, resumen y extracción de tareas automáticas de todas tus reuniones virtuales.", icon: "mic" },
          ],
        },
        {
          id: "02", label: "Automatizaciones",
          desc: "Elimina tareas repetitivas y conecta tus herramientas.",
          items: [
            { title: "Marketing y ventas", desc: "Flujos automáticos de captación y nutrición de leads (CRM).", icon: "funnel" },
            { title: "Atención al cliente", desc: "Ticketing automático y enrutamiento inteligente de consultas.", icon: "ticket" },
            { title: "Administración", desc: "Facturación, contratos y gestión documental sin intervención manual.", icon: "doc" },
            { title: "Recursos humanos", desc: "Onboarding de empleados y gestión de vacaciones automatizada.", icon: "users" },
            { title: "Gestión de proyectos", desc: "Sincronización de tareas entre Trello, Asana, Slack y demás.", icon: "kanban" },
            { title: "Reporting", desc: "Informes semanales generados y enviados automáticamente.", icon: "report" },
          ],
        },
        {
          id: "03", label: "Transformación Digital",
          desc: "Infraestructura digital para el crecimiento.",
          items: [
            { title: "Landing pages", desc: "Diseño web de alto rendimiento enfocado en conversión.", icon: "layout" },
            { title: "Embudos de venta", desc: "Arquitectura de ventas digitales automatizada.", icon: "funnel" },
            { title: "Digitalización", desc: "Migración de procesos analógicos a entornos cloud.", icon: "cloud" },
            { title: "Centralización de datos", desc: "Single Source of Truth para tu empresa.", icon: "db" },
            { title: "Workflows", desc: "Rediseño de flujos de trabajo para máxima productividad.", icon: "flow" },
            { title: "Consultoría estratégica", desc: "Hoja de ruta tecnológica a medida.", icon: "compass" },
          ],
        },
        {
          id: "04", label: "Marketing Digital",
          desc: "Estrategias data-driven para dominar tu mercado.",
          items: [
            { title: "Estrategia 360º", desc: "Planificación omnicanal coherente.", icon: "globe" },
            { title: "Brand communication", desc: "Mensajes que conectan y fidelizan.", icon: "megaphone" },
            { title: "SEO con IA", desc: "Posicionamiento orgánico acelerado.", icon: "search" },
            { title: "Paid media", desc: "Ads optimizados algorítmicamente.", icon: "bullseye" },
            { title: "Growth hacking", desc: "Experimentos rápidos para crecimiento exponencial.", icon: "rocket" },
            { title: "Email marketing", desc: "Secuencias automatizadas de alta conversión.", icon: "mail" },
          ],
        },
      ],
    },
    projects: {
      kicker: "// Algunos de los Últimos Proyectos",
      title: "Casos donde la tecnología ha transformado negocios.",
      note: "Esta sección se irá ampliando con casos de estudio detallados.",
      items: [
        { tag: "VENTAS", title: "Email Marketing con IA", summary: "Automatización e hiperpersonalización del canal de ventas.", chips: ["Email","Automation","IA"], metrics: ["-80% tiempo manual","+200 operaciones auto"], status: "En curso", image: "img/project-email.png", link: "caso-exito-email-marketing.html" },
        { tag: "OPERACIONES", title: "Automatización de procesos", summary: "+50 automatizaciones activas optimizando flujos críticos sin interrupciones.", chips: ["Leads","Data Entry","Comms","RRHH"], metrics: ["+50 procesos activos"], status: "En curso", image: "img/project-automation.png" },
        { tag: "ATENCIÓN CLIENTE", title: "Chatbots y asistentes", summary: "+15 Chatbots desplegados en Web, WhatsApp y Telegram.", chips: ["Chatbot","Multicanal","NLP"], metrics: ["Soporte 24/7","Multicanal"], status: "En curso", image: "img/project-chatbot.png", link: "caso-exito-chatbot-nexia.html" },
        { tag: "MARKETING", title: "RRSS con IA", summary: "3 sistemas de creación de contenido y automatización de redes sociales.", chips: ["Content AI","Automatización","RRSS"], metrics: ["−80% tiempo","+50% consistencia"], status: "En curso", image: "img/project-social.png" },
        { tag: "EDU-TECH", title: "Programas de Formación de Equipos", summary: "Formación y capacitación de equipos en IA, Marketing y Transformación Digital.", chips: ["Formación","IA","Marketing","TD"], metrics: ["IOE Business School"], status: "En curso", image: "img/project-training.png" },
        { tag: "SEGURIDAD", title: "IA privada local", summary: "Modelos open source (Ollama) ejecutados en local para máxima privacidad.", chips: ["Ollama","On-prem","Privacidad"], metrics: ["Datos 100% privados"], status: "En curso", image: "img/project-private.png" },
      ],
    },
    experience: {
      kicker: "// Experiencia",
      title: "Trayectoria profesional.",
      items: [
        { period: "Actualidad", role: "Autónomo · IA, Automatización y Marketing", org: "sergiogp.com", desc: "Servicios freelance de consultoría e implementación en IA para empresas." },
        { period: "Actualidad", role: "Consultoría de Empresas", org: "Brexnet", desc: "Colaboraciones estratégicas en proyectos de Marketing y Escalabilidad Empresarial." },
        { period: "2025 →", role: "Docente · Masterclass de IA", org: "IOE Business School", desc: "Formación a profesionales y empresas en IA aplicada." },
        { period: "Recurrente", role: "Formador Independiente", org: "Independiente", desc: "Acompañamiento formativo personalizado." },
      ],
    },
    education: {
      kicker: "// Formación",
      title: "Formación académica.",
      items: [
        { year: "2025", title: "Programa Agentes del Cambio (Transformación Digital)", org: "ENAE Business School" },
        { year: "2023–2024", title: "Inteligencia Artificial con Python", org: "Harvard University" },
        { year: "2018–2022", title: "Grado en Marketing", org: "Universidad de Murcia" },
      ],
    },
    courses: {
      kicker: "// Cursos & Certificaciones 2024 / 25",
      items: ["IA aplicada al sector turístico","Uso de APIs","Elements of AI","IA Generativa","MAKE: Advanced","Email Marketing","Marketing Automation","Intro: Data Science","IA aplicada al Marketing","Building AI Chatbots without programming","Programación en HTML, CSS y JavaScript","Generative AI: Prompt Engineering Basics"],
    },
    stack: {
      kicker: "// Stack",
      title: "Herramientas con las que trabajo a diario.",
      groups: [
        { label: "IA & LLMs", items: ["OpenAI","Anthropic Claude","Gemini","Ollama","Hugging Face"] },
        { label: "Automatización", items: ["Make","n8n","Zapier","Webhooks","APIs REST"] },
        { label: "Desarrollo", items: ["Python","JavaScript","HTML/CSS","Node.js"] },
        { label: "RAG & Datos", items: ["Pinecone","Supabase","Vector DBs","Embeddings"] },
        { label: "Marketing", items: ["Email Automation","GA4","Meta Ads","SEO"] },
      ],
    },
    skills: {
      kicker: "// Skills",
      title: "Skills.",
      groups: [
        { label: "IA & Automatización", items: ["OpenAI / GPT","Anthropic Claude","Gemini","Ollama","Hugging Face","Make","n8n","Zapier","RAG / Embeddings","Prompt Engineering","Agentes IA","NLP / LLMs"] },
        { label: "Programación", items: ["Python","JavaScript","HTML / CSS","Node.js","APIs REST","SQL","Git","Webhooks","Vector DBs","Supabase","Pinecone","JSON / YAML"] },
        { label: "Marketing & Estrategia", items: ["SEO con IA","Email Marketing","Paid Media","Google Analytics 4","Meta Ads","Growth Hacking","CRM","Embudos de venta","Brand Strategy","Content Marketing","Copywriting","Omnicanalidad"] },
      ],
    },
    languages: {
      kicker: "// Idiomas",
      items: [{ lang: "Español", level: "Nativo" }, { lang: "Inglés", level: "Avanzado" }],
    },
    faq: {
      kicker: "// FAQ",
      title: "Preguntas frecuentes.",
      items: [
        { q: "¿En cuánto tiempo se ven resultados?", a: "Inmediatos tras la implementación. El ROI completo suele consolidarse entre 4-6 meses dependiendo de la escala del proyecto." },
        { q: "¿Necesito conocimientos técnicos?", a: "Para nada. Entrego soluciones llave en mano y formación (know-how) para que tú solo te preocupes de tu negocio." },
        { q: "¿Cuotas mensuales o pago único?", a: "Generalmente trabajo por proyecto (pago único o fraccionado). Para mantenimientos específicos, podemos acordar un fee mensual." },
        { q: "¿Con qué sectores trabajas?", a: "Soy agnóstico al sector. Analizo procesos y datos, que son universales. He trabajado en retail, servicios, industria y más." },
        { q: "¿Puedo empezar con algo pequeño?", a: "Sí. Recomiendo empezar con un Quick Win para validar resultados y luego escalar a soluciones más complejas." },
        { q: "¿Se integra con mis herramientas?", a: "Absolutamente. La prioridad es no romper tu ecosistema actual, sino conectarlo y potenciarlo." },
      ],
    },
    contact: {
      kicker: "// Contacto",
      title: "¿Tienes un proyecto en mente?",
      sub: "Cuéntame el contexto, la respuesta es rápida.",
      cta: "Enviar mensaje",
      formName: "Nombre",
      formEmail: "Email",
      formMessage: "Cuéntame sobre tu proyecto...",
      formSent: "Mensaje enviado. Te responderé pronto.",
    },
    footer: { tagline: "Estrategia, IA y automatización.", rights: "Todos los derechos reservados." },
  },
  en: {
    nav: { home: "Home", about: "About", services: "Services", projects: "Projects", experience: "Experience", education: "Education", stack: "Stack", skills: "Skills", faq: "FAQ", contact: "Contact" },
    hero: {
      role: "Digital Transformation Agent",
      tagline: "Artificial intelligence\nand automation to scale your business.",
      sub: "3+ years optimizing processes and transforming companies. I turn technology into your strongest competitive edge.",
      ctaPrimary: "Free consultation", ctaSecondary: "View services",
      status: "Available for new projects",
    },
    about: {
      kicker: "// About",
      title: "Strategy, AI and automation at the service of your business.",
      body: [
        "I'm Sergio Guillén Pampliega. Trained in Artificial Intelligence, Process Automation, Marketing and Digital Transformation.",
        "My goal is to make companies more efficient and competitive. I do it by freeing up time, building decision-making systems and digitizing key processes.",
        "Every service is tailored to each client and project, ensuring commitment and tangible results. No hype, no over-engineering.",
      ],
      credentials: ["Harvard University", "ENAE Business School", "Universidad de Murcia"],
      stats: [
        { k: "SPECIALIZATION", v: "AI · Automation · Marketing", icon: "brain" },
        { k: "MODE", v: "Freelance · Remote Global", icon: "globe" },
        { k: "LOCATION", v: "Murcia, Spain", icon: "pin" },
      ],
    },
    services: {
      kicker: "// Services", title: "Four areas, one integrated vision.",
      areas: [
        { id: "01", label: "AI Solutions", desc: "AI implementation to maximize efficiency and profitability.",
          items: [
            { title: "Smart chatbots", desc: "24/7 automated customer support with NLP for human, accurate responses.", icon: "chat" },
            { title: "RAG assistants", desc: "Systems that read your internal documentation to instantly answer employee or client queries.", icon: "brain" },
            { title: "Content generation", desc: "Mass, personalized creation of copy, reports and marketing content while keeping your brand voice.", icon: "spark" },
            { title: "Predictive segmentation", desc: "Algorithms that analyze your data to predict purchase behavior and segment audiences.", icon: "target" },
            { title: "Data Analytics & BI", desc: "Interactive dashboards that turn raw data into visual insights for decision making.", icon: "chart" },
            { title: "Meeting Intelligence", desc: "Automatic transcription, summary and task extraction from all your virtual meetings.", icon: "mic" },
          ] },
        { id: "02", label: "Automation", desc: "Eliminate repetitive tasks and connect your tools.",
          items: [
            { title: "Marketing & sales", desc: "Automated flows for lead acquisition and nurturing (CRM).", icon: "funnel" },
            { title: "Customer support", desc: "Automatic ticketing and intelligent query routing.", icon: "ticket" },
            { title: "Administration", desc: "Invoicing, contracts and document management without manual work.", icon: "doc" },
            { title: "HR", desc: "Employee onboarding and time-off management automated.", icon: "users" },
            { title: "Project management", desc: "Task sync across Trello, Asana, Slack and more.", icon: "kanban" },
            { title: "Reporting", desc: "Weekly reports generated and delivered automatically.", icon: "report" },
          ] },
        { id: "03", label: "Digital Transformation", desc: "Digital infrastructure for growth.",
          items: [
            { title: "Landing pages", desc: "High-performance web design focused on conversion.", icon: "layout" },
            { title: "Sales funnels", desc: "Automated digital sales architecture.", icon: "funnel" },
            { title: "Digitization", desc: "Migration of analog processes to cloud environments.", icon: "cloud" },
            { title: "Data centralization", desc: "Single source of truth for your company.", icon: "db" },
            { title: "Workflows", desc: "Workflow redesign for maximum productivity.", icon: "flow" },
            { title: "Strategic consulting", desc: "Tailor-made technology roadmap.", icon: "compass" },
          ] },
        { id: "04", label: "Digital Marketing", desc: "Data-driven strategies to dominate your market.",
          items: [
            { title: "360º strategy", desc: "Coherent omnichannel planning.", icon: "globe" },
            { title: "Brand communication", desc: "Messaging that connects and retains.", icon: "megaphone" },
            { title: "AI-powered SEO", desc: "Accelerated organic positioning.", icon: "search" },
            { title: "Paid media", desc: "Algorithmically optimized ads.", icon: "bullseye" },
            { title: "Growth hacking", desc: "Fast experiments for exponential growth.", icon: "rocket" },
            { title: "Email marketing", desc: "Automated high-conversion sequences.", icon: "mail" },
          ] },
      ],
    },
    projects: {
      kicker: "// Some of the Latest Projects",
      title: "Cases where technology transformed businesses.",
      note: "This section will be expanded with detailed case studies.",
      items: [
        { tag: "SALES", title: "AI Email Marketing", summary: "Automation and hyper-personalization of the sales channel.", chips: ["Email","Automation","AI"], metrics: ["-80% manual time","+200 auto operations"], status: "Ongoing", image: "img/project-email.png", link: "caso-exito-email-marketing.html" },
        { tag: "OPERATIONS", title: "Process automation", summary: "+50 active automations optimizing critical flows without interruption.", chips: ["Leads","Data Entry","Comms","HR"], metrics: ["+50 active processes"], status: "Ongoing", image: "img/project-automation.png" },
        { tag: "CUSTOMER SUPPORT", title: "Chatbots & assistants", summary: "+15 chatbots deployed on Web, WhatsApp and Telegram.", chips: ["Chatbot","Multichannel","NLP"], metrics: ["24/7 support","Multichannel"], status: "Ongoing", image: "img/project-chatbot.png", link: "caso-exito-chatbot-nexia.html" },
        { tag: "MARKETING", title: "Social media with AI", summary: "3 systems for content creation and social media automation.", chips: ["Content AI","Automation","Social"], metrics: ["−80% time","+50% consistency"], status: "Ongoing", image: "img/project-social.png" },
        { tag: "EDU-TECH", title: "Team Training Programs", summary: "Training and upskilling teams in AI, Marketing and Digital Transformation.", chips: ["Training","AI","Marketing","DT"], metrics: ["IOE Business School"], status: "Ongoing", image: "img/project-training.png" },
        { tag: "SECURITY", title: "Local private AI", summary: "Open source models (Ollama) running locally for maximum privacy.", chips: ["Ollama","On-prem","Privacy"], metrics: ["100% private data"], status: "Ongoing", image: "img/project-private.png" },
      ],
    },
    experience: {
      kicker: "// Experience", title: "Professional path.",
      items: [
        { period: "Now", role: "Freelance · AI, Automation & Marketing", org: "sergiogp.com", desc: "Freelance consulting and implementation services in AI for companies." },
        { period: "Now", role: "Business Consulting", org: "Brexnet", desc: "Strategic collaborations in Marketing and Business Scalability projects." },
        { period: "2025 →", role: "Lecturer · AI Masterclass", org: "IOE Business School", desc: "Training professionals and companies on applied AI." },
        { period: "Recurring", role: "Independent Trainer", org: "Independent", desc: "Personalized educational mentoring." },
      ],
    },
    education: {
      kicker: "// Education", title: "Academic background.",
      items: [
        { year: "2025", title: "Change Agents Program (Digital Transformation)", org: "ENAE Business School" },
        { year: "2023–2024", title: "Artificial Intelligence with Python", org: "Harvard University" },
        { year: "2018–2022", title: "Marketing Degree", org: "Universidad de Murcia" },
      ],
    },
    courses: {
      kicker: "// Courses & Certifications 2024 / 25",
      items: ["AI applied to tourism","Working with APIs","Elements of AI","Generative AI","MAKE: Advanced","Email Marketing","Marketing Automation","Intro: Data Science","AI applied to Marketing","Building AI Chatbots without programming","HTML, CSS & JavaScript","Generative AI: Prompt Engineering Basics"],
    },
    stack: {
      kicker: "// Stack", title: "Tools I use day to day.",
      groups: [
        { label: "AI & LLMs", items: ["OpenAI","Anthropic Claude","Gemini","Ollama","Hugging Face"] },
        { label: "Automation", items: ["Make","n8n","Zapier","Webhooks","REST APIs"] },
        { label: "Development", items: ["Python","JavaScript","HTML/CSS","Node.js"] },
        { label: "RAG & Data", items: ["Pinecone","Supabase","Vector DBs","Embeddings"] },
        { label: "Marketing", items: ["Email Automation","GA4","Meta Ads","SEO"] },
      ],
    },
    skills: {
      kicker: "// Skills",
      title: "Skills.",
      groups: [
        { label: "AI & Automation", items: ["OpenAI / GPT","Anthropic Claude","Gemini","Ollama","Hugging Face","Make","n8n","Zapier","RAG / Embeddings","Prompt Engineering","AI Agents","NLP / LLMs"] },
        { label: "Programming", items: ["Python","JavaScript","HTML / CSS","Node.js","REST APIs","SQL","Git","Webhooks","Vector DBs","Supabase","Pinecone","JSON / YAML"] },
        { label: "Marketing & Strategy", items: ["AI-powered SEO","Email Marketing","Paid Media","Google Analytics 4","Meta Ads","Growth Hacking","CRM","Sales Funnels","Brand Strategy","Content Marketing","Copywriting","Omnichannel"] },
      ],
    },
    languages: { kicker: "// Languages", items: [{ lang: "Spanish", level: "Native" }, { lang: "English", level: "Advanced" }] },
    faq: {
      kicker: "// FAQ", title: "Frequently asked questions.",
      items: [
        { q: "How fast do I see results?", a: "Immediately after implementation. Full ROI usually consolidates within 4-6 months depending on the project scale." },
        { q: "Do I need technical knowledge?", a: "Not at all. I deliver turnkey solutions and training so you can focus on your business." },
        { q: "Monthly fee or one-time payment?", a: "I usually work per project (one-time or split payments). For specific maintenance, we can agree on a monthly fee." },
        { q: "Which sectors do you work with?", a: "I'm sector-agnostic. I analyze processes and data, which are universal. I've worked in retail, services, industry and more." },
        { q: "Can I start small?", a: "Yes. I recommend starting with a Quick Win to validate results and then scale to more complex solutions." },
        { q: "Does it integrate with my tools?", a: "Absolutely. The priority is to not break your current ecosystem but to connect and enhance it." },
      ],
    },
    contact: { kicker: "// Contact", title: "Got a project in mind?", sub: "Tell me the context — fast reply.", cta: "Send message", formName: "Name", formEmail: "Email", formMessage: "Tell me about your project...", formSent: "Message sent. I'll get back to you soon." },
    footer: { tagline: "Strategy, AI and automation.", rights: "All rights reserved." },
  },
};
